-- =============================================================
-- Staff (Uzman Personel)
-- =============================================================

-- ---------------------------------------------------------------
-- STAFF ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_STAFF_HIS ON clinic.STAFF;
DROP FUNCTION IF EXISTS clinic.FN_STAFF_HIS();
DROP INDEX IF EXISTS clinic.IDX_STAFF_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS clinic.STAFF_HIS;
DROP SEQUENCE IF EXISTS clinic.SEQ_STAFF_HIS;
DROP INDEX IF EXISTS clinic.IDX_STAFF_LAST_NAME;
DROP INDEX IF EXISTS clinic.IDX_STAFF_STATUS;
DROP TABLE IF EXISTS clinic.STAFF;
DROP SEQUENCE IF EXISTS clinic.SEQ_STAFF;


-- ---------------------------------------------------------------
-- STAFF
-- ---------------------------------------------------------------
CREATE SEQUENCE clinic.SEQ_STAFF START WITH 1 INCREMENT BY 1;

CREATE TABLE clinic.STAFF (
    ID              BIGINT          NOT NULL DEFAULT nextval('clinic.SEQ_STAFF'),
    FIRST_NAME      VARCHAR(100)    NOT NULL,
    LAST_NAME       VARCHAR(100)    NOT NULL,
    TITLE           VARCHAR(100),
    SPECIALIZATION  VARCHAR(200),
    PHONE           VARCHAR(20),
    EMAIL           VARCHAR(150),
    LICENSE_NUMBER  VARCHAR(50),
    HIRE_DATE       DATE,
    NOTE            TEXT,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_STAFF               PRIMARY KEY (ID),
    CONSTRAINT CK_STAFF_STATUS        CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'CANCELLED'))
);

CREATE INDEX IDX_STAFF_STATUS    ON clinic.STAFF (STATUS);
CREATE INDEX IDX_STAFF_LAST_NAME ON clinic.STAFF (LAST_NAME);

CREATE SEQUENCE clinic.SEQ_STAFF_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE clinic.STAFF_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('clinic.SEQ_STAFF_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    FIRST_NAME      VARCHAR(100)    NOT NULL,
    LAST_NAME       VARCHAR(100)    NOT NULL,
    TITLE           VARCHAR(100),
    SPECIALIZATION  VARCHAR(200),
    PHONE           VARCHAR(20),
    EMAIL           VARCHAR(150),
    LICENSE_NUMBER  VARCHAR(50),
    HIRE_DATE       DATE,
    NOTE            TEXT,
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_STAFF_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_STAFF_HIS_ORIGINAL_ID ON clinic.STAFF_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION clinic.FN_STAFF_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO clinic.STAFF_HIS (
            ID, ORIGINAL_ID, FIRST_NAME, LAST_NAME, TITLE, SPECIALIZATION, PHONE, EMAIL,
            LICENSE_NUMBER, HIRE_DATE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_STAFF_HIS'), NEW.ID, NEW.FIRST_NAME, NEW.LAST_NAME, NEW.TITLE, NEW.SPECIALIZATION, NEW.PHONE, NEW.EMAIL,
            NEW.LICENSE_NUMBER, NEW.HIRE_DATE, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO clinic.STAFF_HIS (
            ID, ORIGINAL_ID, FIRST_NAME, LAST_NAME, TITLE, SPECIALIZATION, PHONE, EMAIL,
            LICENSE_NUMBER, HIRE_DATE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_STAFF_HIS'), NEW.ID, NEW.FIRST_NAME, NEW.LAST_NAME, NEW.TITLE, NEW.SPECIALIZATION, NEW.PHONE, NEW.EMAIL,
            NEW.LICENSE_NUMBER, NEW.HIRE_DATE, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO clinic.STAFF_HIS (
            ID, ORIGINAL_ID, FIRST_NAME, LAST_NAME, TITLE, SPECIALIZATION, PHONE, EMAIL,
            LICENSE_NUMBER, HIRE_DATE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_STAFF_HIS'), OLD.ID, OLD.FIRST_NAME, OLD.LAST_NAME, OLD.TITLE, OLD.SPECIALIZATION, OLD.PHONE, OLD.EMAIL,
            OLD.LICENSE_NUMBER, OLD.HIRE_DATE, OLD.NOTE, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_STAFF_HIS
    AFTER INSERT OR UPDATE OR DELETE ON clinic.STAFF
    FOR EACH ROW EXECUTE FUNCTION clinic.FN_STAFF_HIS();
