-- ---------------------------------------------------------------
-- APPOINTMENT: DOCTOR (text) -> STAFF_ID (FK)
-- ---------------------------------------------------------------

-- 1. Yeni kolon ekle
ALTER TABLE clinic.APPOINTMENT ADD COLUMN STAFF_ID BIGINT;

-- 2. FK constraint
ALTER TABLE clinic.APPOINTMENT
    ADD CONSTRAINT FK_APPOINTMENT_STAFF FOREIGN KEY (STAFF_ID) REFERENCES clinic.STAFF(ID);

-- 3. Index
CREATE INDEX IDX_APPOINTMENT_STAFF_ID ON clinic.APPOINTMENT (STAFF_ID);

-- 4. Eski DOCTOR kolonunu kaldır
ALTER TABLE clinic.APPOINTMENT DROP COLUMN DOCTOR;

-- 5. History tablosuna da STAFF_ID ekle, DOCTOR kaldır
ALTER TABLE clinic.APPOINTMENT_HIS ADD COLUMN STAFF_ID BIGINT;
ALTER TABLE clinic.APPOINTMENT_HIS DROP COLUMN DOCTOR;

-- 6. Trigger fonksiyonunu güncelle
CREATE OR REPLACE FUNCTION clinic.FN_APPOINTMENT_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO clinic.APPOINTMENT_HIS (
            ID, ORIGINAL_ID, PATIENT_ID, STAFF_ID, APPOINTMENT_DATE, DURATION_MINUTES, TYPE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_APPOINTMENT_HIS'), NEW.ID, NEW.PATIENT_ID, NEW.STAFF_ID, NEW.APPOINTMENT_DATE, NEW.DURATION_MINUTES, NEW.TYPE, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO clinic.APPOINTMENT_HIS (
            ID, ORIGINAL_ID, PATIENT_ID, STAFF_ID, APPOINTMENT_DATE, DURATION_MINUTES, TYPE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_APPOINTMENT_HIS'), NEW.ID, NEW.PATIENT_ID, NEW.STAFF_ID, NEW.APPOINTMENT_DATE, NEW.DURATION_MINUTES, NEW.TYPE, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO clinic.APPOINTMENT_HIS (
            ID, ORIGINAL_ID, PATIENT_ID, STAFF_ID, APPOINTMENT_DATE, DURATION_MINUTES, TYPE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_APPOINTMENT_HIS'), OLD.ID, OLD.PATIENT_ID, OLD.STAFF_ID, OLD.APPOINTMENT_DATE, OLD.DURATION_MINUTES, OLD.TYPE, OLD.NOTE, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;
