-- =============================================================
-- Patient, Appointment, Treatment Schema
-- =============================================================
-- =============================================================
-- Patient, Appointment, Treatment - ROLLBACK
-- =============================================================

-- ---------------------------------------------------------------
-- TREATMENT ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_TREATMENT_HIS ON clinic.TREATMENT;
DROP FUNCTION IF EXISTS clinic.FN_TREATMENT_HIS();
DROP INDEX IF EXISTS clinic.IDX_TREATMENT_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS clinic.TREATMENT_HIS;
DROP SEQUENCE IF EXISTS clinic.SEQ_TREATMENT_HIS;
DROP INDEX IF EXISTS clinic.IDX_TREATMENT_APPOINTMENT_ID;
DROP INDEX IF EXISTS clinic.IDX_TREATMENT_STATUS;
DROP TABLE IF EXISTS clinic.TREATMENT;
DROP SEQUENCE IF EXISTS clinic.SEQ_TREATMENT;

-- ---------------------------------------------------------------
-- APPOINTMENT ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_APPOINTMENT_HIS ON clinic.APPOINTMENT;
DROP FUNCTION IF EXISTS clinic.FN_APPOINTMENT_HIS();
DROP INDEX IF EXISTS clinic.IDX_APPOINTMENT_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS clinic.APPOINTMENT_HIS;
DROP SEQUENCE IF EXISTS clinic.SEQ_APPOINTMENT_HIS;
DROP INDEX IF EXISTS clinic.IDX_APPOINTMENT_PATIENT_ID;
DROP INDEX IF EXISTS clinic.IDX_APPOINTMENT_DATE;
DROP INDEX IF EXISTS clinic.IDX_APPOINTMENT_STATUS;
DROP TABLE IF EXISTS clinic.APPOINTMENT;
DROP SEQUENCE IF EXISTS clinic.SEQ_APPOINTMENT;

-- ---------------------------------------------------------------
-- PATIENT ROLLBACK
-- ---------------------------------------------------------------
DROP TRIGGER IF EXISTS TRG_PATIENT_HIS ON clinic.PATIENT;
DROP FUNCTION IF EXISTS clinic.FN_PATIENT_HIS();
DROP INDEX IF EXISTS clinic.IDX_PATIENT_HIS_ORIGINAL_ID;
DROP TABLE IF EXISTS clinic.PATIENT_HIS;
DROP SEQUENCE IF EXISTS clinic.SEQ_PATIENT_HIS;
DROP INDEX IF EXISTS clinic.IDX_PATIENT_LAST_NAME;
DROP INDEX IF EXISTS clinic.IDX_PATIENT_STATUS;
DROP TABLE IF EXISTS clinic.PATIENT;
DROP SEQUENCE IF EXISTS clinic.SEQ_PATIENT;


-- ---------------------------------------------------------------
-- PATIENT
-- ---------------------------------------------------------------
CREATE SEQUENCE clinic.SEQ_PATIENT START WITH 1 INCREMENT BY 1;

CREATE TABLE clinic.PATIENT (
    ID              BIGINT          NOT NULL DEFAULT nextval('clinic.SEQ_PATIENT'),
    FIRST_NAME      VARCHAR(100)    NOT NULL,
    LAST_NAME       VARCHAR(100)    NOT NULL,
    BIRTH_DATE      DATE,
    GENDER          VARCHAR(10),
    PHONE           VARCHAR(20),
    EMAIL           VARCHAR(150),
    ADDRESS         VARCHAR(500),
    IDENTITY_NUMBER VARCHAR(20),
    BLOOD_TYPE      VARCHAR(10),
    ALLERGIES       TEXT,
    CHRONIC_DISEASES TEXT,
    NOTE            TEXT,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_PATIENT               PRIMARY KEY (ID),
    CONSTRAINT UK_PATIENT_IDENTITY      UNIQUE (IDENTITY_NUMBER),
    CONSTRAINT CK_PATIENT_STATUS        CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'CANCELLED')),
    CONSTRAINT CK_PATIENT_GENDER        CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER'))
);

CREATE INDEX IDX_PATIENT_STATUS    ON clinic.PATIENT (STATUS);
CREATE INDEX IDX_PATIENT_LAST_NAME ON clinic.PATIENT (LAST_NAME);

CREATE SEQUENCE clinic.SEQ_PATIENT_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE clinic.PATIENT_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('clinic.SEQ_PATIENT_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    FIRST_NAME      VARCHAR(100)    NOT NULL,
    LAST_NAME       VARCHAR(100)    NOT NULL,
    BIRTH_DATE      DATE,
    GENDER          VARCHAR(10),
    PHONE           VARCHAR(20),
    EMAIL           VARCHAR(150),
    ADDRESS         VARCHAR(500),
    IDENTITY_NUMBER VARCHAR(20),
    BLOOD_TYPE      VARCHAR(10),
    ALLERGIES       TEXT,
    CHRONIC_DISEASES TEXT,
    NOTE            TEXT,
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_PATIENT_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_PATIENT_HIS_ORIGINAL_ID ON clinic.PATIENT_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION clinic.FN_PATIENT_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO clinic.PATIENT_HIS (
            ID, ORIGINAL_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL,
            ADDRESS, IDENTITY_NUMBER, BLOOD_TYPE, ALLERGIES, CHRONIC_DISEASES, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_PATIENT_HIS'), NEW.ID, NEW.FIRST_NAME, NEW.LAST_NAME, NEW.BIRTH_DATE, NEW.GENDER, NEW.PHONE, NEW.EMAIL,
            NEW.ADDRESS, NEW.IDENTITY_NUMBER, NEW.BLOOD_TYPE, NEW.ALLERGIES, NEW.CHRONIC_DISEASES, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO clinic.PATIENT_HIS (
            ID, ORIGINAL_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL,
            ADDRESS, IDENTITY_NUMBER, BLOOD_TYPE, ALLERGIES, CHRONIC_DISEASES, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_PATIENT_HIS'), NEW.ID, NEW.FIRST_NAME, NEW.LAST_NAME, NEW.BIRTH_DATE, NEW.GENDER, NEW.PHONE, NEW.EMAIL,
            NEW.ADDRESS, NEW.IDENTITY_NUMBER, NEW.BLOOD_TYPE, NEW.ALLERGIES, NEW.CHRONIC_DISEASES, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO clinic.PATIENT_HIS (
            ID, ORIGINAL_ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, GENDER, PHONE, EMAIL,
            ADDRESS, IDENTITY_NUMBER, BLOOD_TYPE, ALLERGIES, CHRONIC_DISEASES, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_PATIENT_HIS'), OLD.ID, OLD.FIRST_NAME, OLD.LAST_NAME, OLD.BIRTH_DATE, OLD.GENDER, OLD.PHONE, OLD.EMAIL,
            OLD.ADDRESS, OLD.IDENTITY_NUMBER, OLD.BLOOD_TYPE, OLD.ALLERGIES, OLD.CHRONIC_DISEASES, OLD.NOTE, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_PATIENT_HIS
    AFTER INSERT OR UPDATE OR DELETE ON clinic.PATIENT
    FOR EACH ROW EXECUTE FUNCTION clinic.FN_PATIENT_HIS();


-- ---------------------------------------------------------------
-- APPOINTMENT
-- ---------------------------------------------------------------
CREATE SEQUENCE clinic.SEQ_APPOINTMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE clinic.APPOINTMENT (
    ID                  BIGINT          NOT NULL DEFAULT nextval('clinic.SEQ_APPOINTMENT'),
    PATIENT_ID          BIGINT          NOT NULL,
    APPOINTMENT_DATE    TIMESTAMP       NOT NULL,
    DURATION_MINUTES    INTEGER,
    DOCTOR              VARCHAR(150),
    TYPE                VARCHAR(100),
    NOTE                TEXT,
    STATUS              VARCHAR(20)     NOT NULL DEFAULT 'SCHEDULED',
    CREATED_BY          VARCHAR(100)    NOT NULL,
    CREATED_DATE        TIMESTAMP       NOT NULL,
    CREATED_IP          VARCHAR(45)     NOT NULL,
    UPDATED_BY          VARCHAR(100),
    UPDATED_DATE        TIMESTAMP,
    UPDATED_IP          VARCHAR(45),
    CONSTRAINT PK_APPOINTMENT               PRIMARY KEY (ID),
    CONSTRAINT FK_APPOINTMENT_PATIENT       FOREIGN KEY (PATIENT_ID) REFERENCES clinic.PATIENT(ID),
    CONSTRAINT CK_APPOINTMENT_STATUS        CHECK (STATUS IN ('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW'))
);

CREATE INDEX IDX_APPOINTMENT_PATIENT_ID ON clinic.APPOINTMENT (PATIENT_ID);
CREATE INDEX IDX_APPOINTMENT_DATE       ON clinic.APPOINTMENT (APPOINTMENT_DATE);
CREATE INDEX IDX_APPOINTMENT_STATUS     ON clinic.APPOINTMENT (STATUS);

CREATE SEQUENCE clinic.SEQ_APPOINTMENT_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE clinic.APPOINTMENT_HIS (
    ID                  BIGINT          NOT NULL DEFAULT nextval('clinic.SEQ_APPOINTMENT_HIS'),
    ORIGINAL_ID         BIGINT          NOT NULL,
    PATIENT_ID          BIGINT          NOT NULL,
    APPOINTMENT_DATE    TIMESTAMP       NOT NULL,
    DURATION_MINUTES    INTEGER,
    DOCTOR              VARCHAR(150),
    TYPE                VARCHAR(100),
    NOTE                TEXT,
    STATUS              VARCHAR(20)     NOT NULL,
    CREATED_BY          VARCHAR(100)    NOT NULL,
    CREATED_DATE        TIMESTAMP       NOT NULL,
    CREATED_IP          VARCHAR(45)     NOT NULL,
    UPDATED_BY          VARCHAR(100),
    UPDATED_DATE        TIMESTAMP,
    UPDATED_IP          VARCHAR(45),
    DML_OPERATION       VARCHAR(10),
    DML_BY              VARCHAR(100),
    DML_DATE            TIMESTAMP,
    DML_IP              VARCHAR(45),
    CONSTRAINT PK_APPOINTMENT_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_APPOINTMENT_HIS_ORIGINAL_ID ON clinic.APPOINTMENT_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION clinic.FN_APPOINTMENT_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO clinic.APPOINTMENT_HIS (
            ID, ORIGINAL_ID, PATIENT_ID, APPOINTMENT_DATE, DURATION_MINUTES, DOCTOR, TYPE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_APPOINTMENT_HIS'), NEW.ID, NEW.PATIENT_ID, NEW.APPOINTMENT_DATE, NEW.DURATION_MINUTES, NEW.DOCTOR, NEW.TYPE, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO clinic.APPOINTMENT_HIS (
            ID, ORIGINAL_ID, PATIENT_ID, APPOINTMENT_DATE, DURATION_MINUTES, DOCTOR, TYPE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_APPOINTMENT_HIS'), NEW.ID, NEW.PATIENT_ID, NEW.APPOINTMENT_DATE, NEW.DURATION_MINUTES, NEW.DOCTOR, NEW.TYPE, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO clinic.APPOINTMENT_HIS (
            ID, ORIGINAL_ID, PATIENT_ID, APPOINTMENT_DATE, DURATION_MINUTES, DOCTOR, TYPE, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_APPOINTMENT_HIS'), OLD.ID, OLD.PATIENT_ID, OLD.APPOINTMENT_DATE, OLD.DURATION_MINUTES, OLD.DOCTOR, OLD.TYPE, OLD.NOTE, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_APPOINTMENT_HIS
    AFTER INSERT OR UPDATE OR DELETE ON clinic.APPOINTMENT
    FOR EACH ROW EXECUTE FUNCTION clinic.FN_APPOINTMENT_HIS();


-- ---------------------------------------------------------------
-- TREATMENT
-- ---------------------------------------------------------------
CREATE SEQUENCE clinic.SEQ_TREATMENT START WITH 1 INCREMENT BY 1;

CREATE TABLE clinic.TREATMENT (
    ID              BIGINT          NOT NULL DEFAULT nextval('clinic.SEQ_TREATMENT'),
    APPOINTMENT_ID  BIGINT          NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     TEXT,
    TREATMENT_DATE  TIMESTAMP       NOT NULL,
    COST            NUMERIC(12, 2),
    CURRENCY        VARCHAR(10),
    NOTE            TEXT,
    STATUS          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    CONSTRAINT PK_TREATMENT                 PRIMARY KEY (ID),
    CONSTRAINT FK_TREATMENT_APPOINTMENT     FOREIGN KEY (APPOINTMENT_ID) REFERENCES clinic.APPOINTMENT(ID),
    CONSTRAINT CK_TREATMENT_STATUS          CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'CANCELLED'))
);

CREATE INDEX IDX_TREATMENT_APPOINTMENT_ID ON clinic.TREATMENT (APPOINTMENT_ID);
CREATE INDEX IDX_TREATMENT_STATUS         ON clinic.TREATMENT (STATUS);

CREATE SEQUENCE clinic.SEQ_TREATMENT_HIS START WITH 1 INCREMENT BY 1;

CREATE TABLE clinic.TREATMENT_HIS (
    ID              BIGINT          NOT NULL DEFAULT nextval('clinic.SEQ_TREATMENT_HIS'),
    ORIGINAL_ID     BIGINT          NOT NULL,
    APPOINTMENT_ID  BIGINT          NOT NULL,
    NAME            VARCHAR(200)    NOT NULL,
    DESCRIPTION     TEXT,
    TREATMENT_DATE  TIMESTAMP       NOT NULL,
    COST            NUMERIC(12, 2),
    CURRENCY        VARCHAR(10),
    NOTE            TEXT,
    STATUS          VARCHAR(20)     NOT NULL,
    CREATED_BY      VARCHAR(100)    NOT NULL,
    CREATED_DATE    TIMESTAMP       NOT NULL,
    CREATED_IP      VARCHAR(45)     NOT NULL,
    UPDATED_BY      VARCHAR(100),
    UPDATED_DATE    TIMESTAMP,
    UPDATED_IP      VARCHAR(45),
    DML_OPERATION   VARCHAR(10),
    DML_BY          VARCHAR(100),
    DML_DATE        TIMESTAMP,
    DML_IP          VARCHAR(45),
    CONSTRAINT PK_TREATMENT_HIS PRIMARY KEY (ID)
);

CREATE INDEX IDX_TREATMENT_HIS_ORIGINAL_ID ON clinic.TREATMENT_HIS (ORIGINAL_ID);

CREATE OR REPLACE FUNCTION clinic.FN_TREATMENT_HIS()
RETURNS TRIGGER AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO clinic.TREATMENT_HIS (
            ID, ORIGINAL_ID, APPOINTMENT_ID, NAME, DESCRIPTION, TREATMENT_DATE, COST, CURRENCY, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_TREATMENT_HIS'), NEW.ID, NEW.APPOINTMENT_ID, NEW.NAME, NEW.DESCRIPTION, NEW.TREATMENT_DATE, NEW.COST, NEW.CURRENCY, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'INSERT', NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'UPDATE') THEN
        INSERT INTO clinic.TREATMENT_HIS (
            ID, ORIGINAL_ID, APPOINTMENT_ID, NAME, DESCRIPTION, TREATMENT_DATE, COST, CURRENCY, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_TREATMENT_HIS'), NEW.ID, NEW.APPOINTMENT_ID, NEW.NAME, NEW.DESCRIPTION, NEW.TREATMENT_DATE, NEW.COST, NEW.CURRENCY, NEW.NOTE, NEW.STATUS,
            NEW.CREATED_BY, NEW.CREATED_DATE, NEW.CREATED_IP, NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP,
            'UPDATE', NEW.UPDATED_BY, NEW.UPDATED_DATE, NEW.UPDATED_IP
        );
        RETURN NEW;
    ELSIF (TG_OP = 'DELETE') THEN
        INSERT INTO clinic.TREATMENT_HIS (
            ID, ORIGINAL_ID, APPOINTMENT_ID, NAME, DESCRIPTION, TREATMENT_DATE, COST, CURRENCY, NOTE, STATUS,
            CREATED_BY, CREATED_DATE, CREATED_IP, UPDATED_BY, UPDATED_DATE, UPDATED_IP,
            DML_OPERATION, DML_BY, DML_DATE, DML_IP
        ) VALUES (
            nextval('clinic.SEQ_TREATMENT_HIS'), OLD.ID, OLD.APPOINTMENT_ID, OLD.NAME, OLD.DESCRIPTION, OLD.TREATMENT_DATE, OLD.COST, OLD.CURRENCY, OLD.NOTE, OLD.STATUS,
            OLD.CREATED_BY, OLD.CREATED_DATE, OLD.CREATED_IP, OLD.UPDATED_BY, OLD.UPDATED_DATE, OLD.UPDATED_IP,
            'DELETE', COALESCE(OLD.UPDATED_BY, OLD.CREATED_BY), COALESCE(OLD.UPDATED_DATE, OLD.CREATED_DATE), COALESCE(OLD.UPDATED_IP, OLD.CREATED_IP)
        );
        RETURN OLD;
    END IF;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_TREATMENT_HIS
    AFTER INSERT OR UPDATE OR DELETE ON clinic.TREATMENT
    FOR EACH ROW EXECUTE FUNCTION clinic.FN_TREATMENT_HIS();
